# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Aluno\Documents\PSoC Creator\BCC722-PRATICA-03\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\Pratica03-uCOS-III.cydsn\Pratica03-uCOS-III.cyprj
# Date: Fri, 23 Sep 2022 19:35:49 GMT
#set_units -time ns


# Component constraints for C:\Users\Aluno\Documents\PSoC Creator\BCC722-PRATICA-03\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\Pratica03-uCOS-III.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Aluno\Documents\PSoC Creator\BCC722-PRATICA-03\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\Pratica03-uCOS-III.cydsn\Pratica03-uCOS-III.cyprj
# Date: Fri, 23 Sep 2022 19:35:45 GMT
