/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_Status.h"
#include "LED_aliases.h"
#include "LED.h"
#include "LCD_Disp.h"
#include "PB_2_aliases.h"
#include "PB_2.h"
#include "ProbeUART.h"
#include "ProbeUART_Rx_aliases.h"
#include "ProbeUART_Rx.h"
#include "ProbeUART_Tx_aliases.h"
#include "ProbeUART_Tx.h"
#include "ProbeUART_TxISR.h"
#include "ProbeUART_RxISR.h"
#include "PB_3_aliases.h"
#include "PB_3.h"
#include "se_indut_porta_aliases.h"
#include "se_indut_porta.h"
#include "se_indut_grade_aliases.h"
#include "se_indut_grade.h"
#include "se_temp_motor_aliases.h"
#include "se_temp_motor.h"
#include "se_temp_quadro_aliases.h"
#include "se_temp_quadro.h"
#include "bt_liga_aliases.h"
#include "bt_liga.h"
#include "si_liga_aliases.h"
#include "si_liga.h"
#include "si_desl_aliases.h"
#include "si_desl.h"
#include "si_rearme_aliases.h"
#include "si_rearme.h"
#include "si_emerg_aliases.h"
#include "si_emerg.h"
#include "si_alerta_aliases.h"
#include "si_alerta.h"
#include "al_buzzer_aliases.h"
#include "al_buzzer.h"
#include "bt_desl_aliases.h"
#include "bt_desl.h"
#include "bt_rearme_aliases.h"
#include "bt_rearme.h"
#include "bt_emerg_aliases.h"
#include "bt_emerg.h"
#include "bt_emerg_int.h"
#include "se_indut_porta_int.h"
#include "se_indut_grade_int.h"
#include "LCD_Disp_LCDPort_aliases.h"
#include "LCD_Disp_LCDPort.h"
#include "ProbeUART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

