# THIS FILE IS AUTOMATICALLY GENERATED
# Project: H:\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\uCOS-III-Probe.cyprj
# Date: Sun, 23 Oct 2022 00:36:58 GMT
#set_units -time ns


# Component constraints for H:\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\TopDesign\TopDesign.cysch
# Project: H:\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\uCOS-III-Probe.cyprj
# Date: Sun, 23 Oct 2022 00:36:52 GMT
