# THIS FILE IS AUTOMATICALLY GENERATED
# Project: Y:\UFOP\BCC722\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\uCOS-III-Probe.cyprj
# Date: Wed, 19 Oct 2022 15:46:30 GMT
#set_units -time ns


# Component constraints for Y:\UFOP\BCC722\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\TopDesign\TopDesign.cysch
# Project: Y:\UFOP\BCC722\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\uCOS-III-Probe.cyprj
# Date: Wed, 19 Oct 2022 15:46:11 GMT
