# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\alex\Documents\PSoC Creator\BCC722-PRATICA-03\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\uCOS-III-Probe.cyprj
# Date: Fri, 23 Sep 2022 15:21:47 GMT
#set_units -time ns


# Component constraints for C:\Users\alex\Documents\PSoC Creator\BCC722-PRATICA-03\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\alex\Documents\PSoC Creator\BCC722-PRATICA-03\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\uCOS-III-Probe.cydsn\uCOS-III-Probe.cyprj
# Date: Fri, 23 Sep 2022 15:21:41 GMT
