# THIS FILE IS AUTOMATICALLY GENERATED
# Project: H:\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\BCC722-RTOS-MOINHO.cydsn\BCC722-RTOS-MOINHO.cyprj
# Date: Sun, 23 Oct 2022 00:36:28 GMT
#set_units -time ns
create_clock -name {ADC_SAR_Seq_IntClock(routed)} -period 633.33333333333326 -waveform {0 316.666666666667} [list [get_pins {ClockBlock/dclk_0}]]


# Component constraints for H:\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\BCC722-RTOS-MOINHO.cydsn\TopDesign\TopDesign.cysch
# Project: H:\BCC722-RTOS-moinho\UCoS\Micrium_2\Software\EvalBoards\Cypress\CY8CKIT-050\PSoC\uCOS-III-Probe\BCC722-RTOS-MOINHO.cydsn\BCC722-RTOS-MOINHO.cyprj
# Date: Sun, 23 Oct 2022 00:36:09 GMT
